name: Kotlin CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.4.2
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.4.1
        with:
          arguments: buildFatJar
